/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blackjackbutbetter;
import java.util.Random;
import java.util.ArrayList;
/**
 *
 * @author brandoncotton
 */
public class BlackjackGUI extends javax.swing.JFrame {
Random rand = new Random();
//Stores the cards that the player and dealer have.
ArrayList PlayerHand = new ArrayList<Card>();
ArrayList DealerHand = new ArrayList<Card>();
//The Actual score during the rounds
int PlayerScore = 0;
int DealerScore = 0;
//The amount of money left
int PlayerMoney = 500;
int DealerMoney = 500;
//The Actual bet between rounds. Cannot go below 10 or above the player's current money.
int Bet = 100;
//Tells what cards the player and dealer have
String DealerCards = "";
String PlayerCards = "";


  /**
   * Creates new form blackjackGUI
   */
  public BlackjackGUI() {
    initComponents();
    btnHit.setVisible(false);
    btnStand.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    lblDealerMoney = new javax.swing.JLabel();
    lblDealer = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    lblPlayerMoney = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    btnHit = new javax.swing.JButton();
    btnStand = new javax.swing.JButton();
    btnReset = new javax.swing.JButton();
    lblDHand = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    lblDealerTotal = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    lblPlayerpanel = new javax.swing.JPanel();
    lblPlayerTotal = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    lblDealerHandLabel = new javax.swing.JLabel();
    lblPHand = new javax.swing.JLabel();
    lblPlayerHandLabel = new javax.swing.JLabel();
    btnStart = new javax.swing.JButton();
    lblBetLabel = new javax.swing.JLabel();
    btnPlus = new javax.swing.JButton();
    btnMinus = new javax.swing.JButton();
    lblBet = new javax.swing.JLabel();
    lblStatus = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    lblDealerMoney.setText("500");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(lblDealerMoney)
        .addContainerGap(31, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(19, Short.MAX_VALUE)
        .addComponent(lblDealerMoney)
        .addGap(16, 16, 16))
    );

    lblDealer.setText("Dealer");

    jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    lblPlayerMoney.setText("500");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(lblPlayerMoney)
        .addContainerGap(24, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(19, Short.MAX_VALUE)
        .addComponent(lblPlayerMoney)
        .addGap(16, 16, 16))
    );

    jLabel1.setText("You");

    btnHit.setText("Hit");
    btnHit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHitActionPerformed(evt);
      }
    });

    btnStand.setText("Stand");
    btnStand.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnStandActionPerformed(evt);
      }
    });

    btnReset.setText("Reset");
    btnReset.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnResetActionPerformed(evt);
      }
    });

    lblDHand.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    lblDealerTotal.setText("??");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(lblDealerTotal)
        .addContainerGap(31, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap(19, Short.MAX_VALUE)
        .addComponent(lblDealerTotal)
        .addGap(16, 16, 16))
    );

    jLabel2.setText("Dealer Total");

    lblPlayerpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    lblPlayerTotal.setText("??");

    javax.swing.GroupLayout lblPlayerpanelLayout = new javax.swing.GroupLayout(lblPlayerpanel);
    lblPlayerpanel.setLayout(lblPlayerpanelLayout);
    lblPlayerpanelLayout.setHorizontalGroup(
      lblPlayerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(lblPlayerpanelLayout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(lblPlayerTotal)
        .addContainerGap(31, Short.MAX_VALUE))
    );
    lblPlayerpanelLayout.setVerticalGroup(
      lblPlayerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblPlayerpanelLayout.createSequentialGroup()
        .addContainerGap(19, Short.MAX_VALUE)
        .addComponent(lblPlayerTotal)
        .addGap(16, 16, 16))
    );

    jLabel3.setText("Your Total");

    lblDealerHandLabel.setText("Dealer's Hand");

    lblPHand.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    lblPlayerHandLabel.setText("Your Hand");

    btnStart.setText("Start");
    btnStart.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnStartActionPerformed(evt);
      }
    });

    lblBetLabel.setText("Bet");

    btnPlus.setText("+10");
    btnPlus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPlusActionPerformed(evt);
      }
    });

    btnMinus.setText("-10");
    btnMinus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnMinusActionPerformed(evt);
      }
    });

    lblBet.setText("100");
    lblBet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    lblStatus.setText("jLabel4");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(224, 224, 224)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblDHand, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblDealerHandLabel))
              .addComponent(lblPHand, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(150, 150, 150)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblDealer))))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(lblPlayerHandLabel))
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel1)
                    .addGap(39, 39, 39)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(btnHit)
                      .addComponent(btnStand)))
                  .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                      .addComponent(lblBetLabel)
                      .addComponent(lblBet)))))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnStart)
                .addGap(26, 26, 26)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(lblPlayerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(8, 8, 8)))))
        .addGap(17, 17, 17))
      .addGroup(layout.createSequentialGroup()
        .addGap(268, 268, 268)
        .addComponent(lblStatus)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblDealer)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblDealerHandLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblDHand, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(30, 30, 30)
        .addComponent(lblStatus)
        .addGap(32, 32, 32)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblPlayerHandLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblPHand, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblBetLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(btnPlus)
                  .addComponent(btnMinus))
                .addGap(0, 0, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(12, 12, 12)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(btnHit)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnStand)))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btnStart)
              .addComponent(btnReset)))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblPlayerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(35, 35, 35))))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void dealerAction(){
    boolean stand = false;
    while(!stand){
      Card card = cardCreate();
      DealerHand.add(card);
      DealerCards += card.getNumDisplay() + " ";
      DealerScore = scoreCount(DealerHand);
      if(DealerScore >= 21){
        stand = true;
      }
      else if(DealerScore >=16 && rand.nextInt(10) > 6){
        stand = true;
      }
      else if(DealerScore >= 12 && rand.nextInt(10) < 3){
        stand = true;
      }
    }
    lblDHand.setText("? ? ? ? ?");
  }
  
  private void btnHitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitActionPerformed
    Card card = cardCreate();
    lblStatus.setText("You got " + card.toString());
    PlayerHand.add(card);
    PlayerCards += card.getNumDisplay() + " ";
    lblPHand.setText(PlayerCards);
    PlayerScore = scoreCount(PlayerHand);
    lblPlayerTotal.setText(Integer.toString(PlayerScore));
    if(PlayerScore >= 21){
      Result();
    }
  }//GEN-LAST:event_btnHitActionPerformed

  private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
    nextRound();
    dealerAction();
    buttonsVisible();
  }//GEN-LAST:event_btnStartActionPerformed

  private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
    if(Bet > 10 && Bet !=0){
     Bet -= 10;
    }
    lblBet.setText(Integer.toString(Bet));
  }//GEN-LAST:event_btnMinusActionPerformed

  private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
    if(Bet < PlayerMoney && Bet != 0){
      Bet += 10;
    }
    lblBet.setText(Integer.toString(Bet));
  }//GEN-LAST:event_btnPlusActionPerformed

  private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    PlayerMoney = 500;
    DealerMoney = 500;
    Bet = 100;
    lblPlayerMoney.setText("500");
    lblDealerMoney.setText("500");
    lblBet.setText("100");
    btnStart.setVisible(true);
    btnPlus.setVisible(true);
    btnMinus.setVisible(true);
    nextRound();
  }//GEN-LAST:event_btnResetActionPerformed

  public void nextRound(){
    PlayerScore = 0;
    DealerScore = 0;
    lblPlayerTotal.setText("0");
    lblDealerTotal.setText("0");
    lblPHand.setText("");
    lblDHand.setText("");
    PlayerHand.clear();
    DealerHand.clear();
    PlayerCards = "";
    DealerCards = "";
    lblStatus.setText("");
  }
  
  private void btnStandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStandActionPerformed
    Result();
  }//GEN-LAST:event_btnStandActionPerformed

  public void PlayerWin(){
    PlayerMoney += Bet;
    DealerMoney -= Bet;
  }
  
  public void DealerWin(){
    PlayerMoney -= Bet;
    DealerMoney += Bet;
  }
  
  //Calculates the results of this round.
  public void Result(){
    buttonsVisible();
    lblDealerTotal.setText(Integer.toString(DealerScore));
    lblDHand.setText(DealerCards);
    //Dealer Busts
    if(PlayerScore <= 21 && DealerScore > 21){
      lblStatus.setText("Dealer busted. You win!");
      PlayerWin();
    }
    //Player busts
    else if(PlayerScore > 21 && DealerScore <= 21){
      lblStatus.setText("You busted. Dealer wins...");
      DealerWin();
    }
    //Every either busted or tied
    else if((PlayerScore > 21 && DealerScore > 21) || (PlayerScore == DealerScore) ){
      lblStatus.setText("Nobody wins.");
    }
    //PLayer wins
    else if(PlayerScore > DealerScore){
      lblStatus.setText("You win!");
      PlayerWin();
    }
    //Dealer wins
    else{
      lblStatus.setText("Dealer wins...");
      DealerWin();
    }
    
    lblPlayerMoney.setText(Integer.toString(PlayerMoney));
    lblDealerMoney.setText(Integer.toString(DealerMoney));
    
    if(PlayerMoney == 0){
      lblStatus.setText("You have no more money. Game over.");
      gameEnd();
    }
    else if(DealerMoney == 0){
      lblStatus.setText("The Dealer's out of money. You win!");
      gameEnd();
    }
    
    if(Bet > PlayerMoney){
      Bet = PlayerMoney;
    }
    else if(Bet > DealerMoney){
      Bet = DealerMoney;
    }
    
    lblBet.setText(Integer.toString(Bet));
  }
  
  //Hides every active button except for reset because the game is over
  private void gameEnd(){
    btnStart.setVisible(false);
    btnPlus.setVisible(false);
    btnMinus.setVisible(false);
  }
  
  //switches every button to be visible if it not visible and invisible if it is visible
  private void buttonsVisible(){
    btnHit.setVisible(!btnHit.isVisible());
    btnStand.setVisible(!btnStand.isVisible());
    btnStart.setVisible(!btnStart.isVisible());
    btnPlus.setVisible(!btnPlus.isVisible());
    btnMinus.setVisible(!btnMinus.isVisible());
  }
  
  //creates a card. If someone already has this card, then it creates a different card.
  public Card cardCreate(){
    String[] suits = {"Hearts","Clubs","Diamonds","Spades"};
    Card card = new Card(suits[rand.nextInt(4)],rand.nextInt(13)+1);
    if(PlayerHand.contains(card) || DealerHand.contains(card)){
      card = cardCreate();
    }
    return card;
  }
  
  //returns the score for the hand it is given
  public int scoreCount(ArrayList<Card> hand){
    int total = 0;
    int i;
    for(i = 0; i < hand.size(); i++){
      total += hand.get(i).getValue();
    }
    //if the score is over 21 and we have an ace, then we turn the ace's value to 1 instead of 11.
    if(total > 21){
      for(i = 0;i<hand.size();i++){
        if(hand.get(i).getNumDisplay()=="Ace" && hand.get(i).getValue() == 11){
          hand.get(i).setValue(1);
          total -= 10;
        }
      }
    }
    return total;
  }
    
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new BlackjackGUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnHit;
  private javax.swing.JButton btnMinus;
  private javax.swing.JButton btnPlus;
  private javax.swing.JButton btnReset;
  private javax.swing.JButton btnStand;
  private javax.swing.JButton btnStart;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JLabel lblBet;
  private javax.swing.JLabel lblBetLabel;
  private javax.swing.JLabel lblDHand;
  private javax.swing.JLabel lblDealer;
  private javax.swing.JLabel lblDealerHandLabel;
  private javax.swing.JLabel lblDealerMoney;
  private javax.swing.JLabel lblDealerTotal;
  private javax.swing.JLabel lblPHand;
  private javax.swing.JLabel lblPlayerHandLabel;
  private javax.swing.JLabel lblPlayerMoney;
  private javax.swing.JLabel lblPlayerTotal;
  private javax.swing.JPanel lblPlayerpanel;
  private javax.swing.JLabel lblStatus;
  // End of variables declaration//GEN-END:variables
}
